name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.15'

      - name: Install Poetry
        run: |
          pip3 install poetry==1.1.15

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with Flake8
        run: |
          poetry run flake8 . --max-line-length 120

      - name: Format with Black
        run: |
          poetry run black --check .

      - name: Sort imports with isort
        run: |
          poetry run isort -rc .

      - name: Test with pytest
        run: |
          poetry run pytest tests/
